# Assignment 2

## Question 1

In [1]:
import numpy as np
arr1=np.arange(1,11,1)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
arr2=arr1.reshape(2,5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Question 2

In [3]:
import numpy as np
arr1=np.arange(1,21,1)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# items between 5th and 15th index meaning between 6th and 16th elements meaning from 7 to 15

In [4]:
print(arr1[6:15])

[ 7  8  9 10 11 12 13 14 15]


## Question 3

In [6]:
import numpy as np
arr1=np.arange(1,21,1)

mean=np.mean(arr1)
print(mean)

10.5


In [7]:
median=np.median(arr1)
print(median)

10.5


In [8]:
SD=np.std(arr1)
print(SD)

5.766281297335398


## Question 4

In [9]:
import numpy as np
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


or

In [10]:
import numpy as np
arr=np.arange(1,13)
x=arr.reshape(3,4)
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
y=np.array([5,8,3,4])
print(y)

[5 8 3 4]


In [12]:
diff=x-y
print(diff)

[[-4 -6  0  0]
 [ 0 -2  4  4]
 [ 4  2  8  8]]


## Question 5

In [13]:
import pandas as pd
data={
'Name':['Ajesh','Keerthana','Geethu','Stejin','Teena','Vishnu','Anjana','Rahul','Nandu','Jerin'],
'Age':[35,33,32,33,29,38,26,43,25,30],
'Gender':['M','F','F','M','F','M','F','M','M','M']}
df=pd.DataFrame(data)
df

,Name,Age,Gender
0,Ajesh,35,M
1,Keerthana,33,F
2,Geethu,32,F
3,Stejin,33,M
4,Teena,29,F
5,Vishnu,38,M
6,Anjana,26,F
7,Rahul,43,M
8,Nandu,25,M
9,Jerin,30,M


### Subquestion 1

In [14]:
df['Occupation']=['Manager','Manager','Analyst','Programmer','Analyst','Analyst','Programmer','Manager','Analyst','Programmer']
df

,Name,Age,Gender,Occupation
0,Ajesh,35,M,Manager
1,Keerthana,33,F,Manager
2,Geethu,32,F,Analyst
3,Stejin,33,M,Programmer
4,Teena,29,F,Analyst
5,Vishnu,38,M,Analyst
6,Anjana,26,F,Programmer
7,Rahul,43,M,Manager
8,Nandu,25,M,Analyst
9,Jerin,30,M,Programmer


### Subquestion 2

In [15]:
df[df['Age']>=30]

,Name,Age,Gender,Occupation
0,Ajesh,35,M,Manager
1,Keerthana,33,F,Manager
2,Geethu,32,F,Analyst
3,Stejin,33,M,Programmer
5,Vishnu,38,M,Analyst
7,Rahul,43,M,Manager
9,Jerin,30,M,Programmer


### Subquestion 3

In [16]:
df.to_csv("Employee details.csv",index=False)

In [17]:
df1=pd.read_csv("Employee details.csv")
df1

,Name,Age,Gender,Occupation
0,Ajesh,35,M,Manager
1,Keerthana,33,F,Manager
2,Geethu,32,F,Analyst
3,Stejin,33,M,Programmer
4,Teena,29,F,Analyst
5,Vishnu,38,M,Analyst
6,Anjana,26,F,Programmer
7,Rahul,43,M,Manager
8,Nandu,25,M,Analyst
9,Jerin,30,M,Programmer
